import cloudinary from '../src/config/cloudinary';
import * as fs from 'fs';
import * as path from 'path';

const frontendDir = path.resolve(__dirname, '../../frontend/src');

// Get all TypeScript/TSX files
const getAllCodeFiles = (dirPath: string, arrayOfFiles: string[] = []) => {
  if (!fs.existsSync(dirPath)) return arrayOfFiles;
  const files = fs.readdirSync(dirPath);
  files.forEach(function(file) {
    if (fs.statSync(dirPath + "/" + file).isDirectory()) {
      arrayOfFiles = getAllCodeFiles(dirPath + "/" + file, arrayOfFiles);
    } else {
      if (file.endsWith('.tsx') || file.endsWith('.ts')) {
        arrayOfFiles.push(path.join(dirPath, "/", file));
      }
    }
  });
  return arrayOfFiles;
};

const replaceAssets = async () => {
  console.log("🚀 Fetching Cloudinary mapping...");
  
  try {
    let allResources: any[] = [];
    let nextCursor = null;
    
    // Fetch all resources (handling pagination if > 500)
    do {
      const result: any = await cloudinary.api.resources({
        type: 'upload',
        prefix: 'adventurer_assets_migration',
        max_results: 500,
        next_cursor: nextCursor
      });
      allResources = allResources.concat(result.resources);
      nextCursor = result.next_cursor;
    } while (nextCursor);

    console.log(`✅ Found ${allResources.length} assets on Cloudinary`);

    // Create a mapping from original_filename -> secure_url
    const mapping: Record<string, string> = {};
    for (const res of allResources) {
      // Cloudinary public_id looks like: adventurer_assets_migration/images/hariharfort_xyz123
      const basename = path.basename(res.public_id);
      
      // We need to strip the random 6 character suffix generated by use_filename: true
      // e.g. hariharfort_xyz123 -> hariharfort
      const lastUnderscore = basename.lastIndexOf('_');
      if (lastUnderscore !== -1) {
        const originalName = basename.substring(0, lastUnderscore).toLowerCase();
        
        // Optimize URL with q_auto,f_auto if image, or q_auto if video
        let optimizedUrl = res.secure_url;
        if (res.resource_type === 'image') {
          optimizedUrl = optimizedUrl.replace('/upload/', '/upload/q_auto,f_auto/');
        } else if (res.resource_type === 'video') {
          optimizedUrl = optimizedUrl.replace('/upload/', '/upload/q_auto/');
        }
        
        mapping[originalName] = optimizedUrl;
      }
    }

    const files = getAllCodeFiles(frontendDir);
    console.log(`🔍 Scanning ${files.length} codebase files for replacements...`);
    console.log(`Debug mapping keys (first 10):`, Object.keys(mapping).slice(0, 10));

    let totalReplacements = 0;

    for (const file of files) {
      let content = fs.readFileSync(file, 'utf8');
      let modified = false;

      // Find all strings that match /assets/... or "/assets/..."
      // Regex matches: /assets/path/to/filename.ext
      const assetRegex = /\/assets\/[^"'\s`]+(?:\.(?:jpg|jpeg|png|webp|gif|mp4|svg|mp3))/gi;
      
      const matches = content.match(assetRegex);
      if (matches) {
        for (const match of matches) {
          const basename = path.basename(match);
          const ext = path.extname(basename);
          const filenameWithoutExt = path.basename(basename, ext).toLowerCase();
          const decoded = decodeURIComponent(filenameWithoutExt);

          if (mapping[filenameWithoutExt]) {
            content = content.replace(match, mapping[filenameWithoutExt]);
            modified = true;
            totalReplacements++;
          } else if (mapping[decoded]) {
            content = content.replace(match, mapping[decoded]);
            modified = true;
            totalReplacements++;
          } else {
             // Debug log
             console.log(`Missing in mapping: ${match} -> tried key: '${filenameWithoutExt}' or '${decoded}'`);
          }
        }
      }

      if (modified) {
        fs.writeFileSync(file, content, 'utf8');
        console.log(`📝 Updated: ${path.basename(file)}`);
      }
    }

    console.log(`🎉 Done! Total URLs replaced: ${totalReplacements}`);
  } catch (error) {
    console.error("❌ Failed to replace assets:", error);
  }
};

replaceAssets();
